version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  joblisting-application:
    image: 234194605782.dkr.ecr.ap-south-1.amazonaws.com/joblisting-application:latest
    container_name: joblisting-application
    ports:
      - 8080:8080
    links:
      - mongodb